In [5]:
import svgpathtools
import numpy as np

In [2]:
path_to_file = 'A.svg'
path,_=svgpathtools.svg2paths(path_to_file)

In [3]:
path

[Path(Line(start=(62.868614+46.826283j), end=(151.31825+46.826283j)),
      Line(start=(151.31825+46.826283j), end=(151.31825+109.69489j)),
      Line(start=(151.31825+109.69489j), end=(62.868614+109.69489j)),
      Line(start=(62.868614+109.69489j), end=(62.868614+46.826283j)))]

In [23]:
path[0]

Path(Line(start=(62.868614+46.826283j), end=(151.31825+46.826283j)),
     Line(start=(151.31825+46.826283j), end=(151.31825+109.69489j)),
     Line(start=(151.31825+109.69489j), end=(62.868614+109.69489j)),
     Line(start=(62.868614+109.69489j), end=(62.868614+46.826283j)))

In [27]:
((151.31825-62.868614)+(109.69489-46.826283))*2

302.636486

In [24]:
path[0].length()

302.636486

In [40]:
path_to_file = 'A.svg'
path,_=svgpathtools.svg2paths(path_to_file)
path = path[0]

points=np.linspace(0,1,10,endpoint=True)
pathvals=np.zeros_like(points,dtype="complex")

pathlength=path.length()
for i in range(len(points)):
    """
    先获取路径物理长度的百分比所对应的长度
    然后再获取该百分比长度对应的百分比
    """
    pathvals[i]=path.point(path.ilength(pathlength*points[i]))
    
pathvals=np.conj(pathvals).copy()
pathvals

array([ 62.868614   -46.826283j  ,  96.49489022 -46.826283j  ,
       130.12116644 -46.826283j  , 151.31825    -59.25547567j,
       151.31825    -92.88175189j, 134.50511189-109.69489j   ,
       100.87883567-109.69489j   ,  67.25255944-109.69489j   ,
        62.868614   -80.45255922j,  62.868614   -46.826283j  ])

In [29]:
points

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
pathvals

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j])

In [30]:
com_list = [1+2j, 3+4j, 5+6j]
np.conj(com_list)

array([1.-2.j, 3.-4.j, 5.-6.j])

In [36]:
nvec = 11
coefs=list(range(nvec // 2, -nvec// 2, -1))
coefs.sort(key=abs)
coefs

[0, 1, -1, 2, -2, 3, -3, 4, -4, 5, -5]

In [37]:
np.array(coefs)

array([ 0,  1, -1,  2, -2,  3, -3,  4, -4,  5, -5])

In [35]:
import numpy as np

# 示例数据
y = np.array([1, 2, 3, 4])
x = np.array([0, 1, 2, 3])

# 使用 np.trapz 计算积分
integral = np.trapz(y, x)

print(integral)


7.5
