In [5]:
import svgpathtools
import numpy as np

In [2]:
path_to_file = 'A.svg'
path,_=svgpathtools.svg2paths(path_to_file)

In [3]:
path

[Path(Line(start=(62.868614+46.826283j), end=(151.31825+46.826283j)),
      Line(start=(151.31825+46.826283j), end=(151.31825+109.69489j)),
      Line(start=(151.31825+109.69489j), end=(62.868614+109.69489j)),
      Line(start=(62.868614+109.69489j), end=(62.868614+46.826283j)))]

In [23]:
path[0]

Path(Line(start=(62.868614+46.826283j), end=(151.31825+46.826283j)),
     Line(start=(151.31825+46.826283j), end=(151.31825+109.69489j)),
     Line(start=(151.31825+109.69489j), end=(62.868614+109.69489j)),
     Line(start=(62.868614+109.69489j), end=(62.868614+46.826283j)))

In [27]:
((151.31825-62.868614)+(109.69489-46.826283))*2

302.636486

In [24]:
path[0].length()

302.636486

In [42]:
path_to_file = 'A44.svg'
path,_=svgpathtools.svg2paths(path_to_file)
path = path[0]

points=np.linspace(0,1,10,endpoint=True)
pathvals=np.zeros_like(points,dtype="complex")

pathlength=path.length()
for i in range(len(points)):
    """
    先获取路径物理长度的百分比所对应的长度
    然后再获取该百分比长度对应的百分比
    """
    pathvals[i]=path.point(path.ilength(pathlength*points[i]))

pathvals=np.conj(pathvals).copy()
pathvals

array([191.16124   -224.86824j   , 129.16432005-180.93497713j,
       105.22785324 -93.30791839j,  90.72532532-141.67572027j,
        48.35844438-221.23150612j,  60.71617042-194.1063639j ,
        86.41654405-107.05398484j, 107.75655021 -71.91411715j,
       129.35665661-159.85734368j, 191.16124   -224.86824j   ])

In [64]:
path_to_file = 'A.svg'
path,_=svgpathtools.svg2paths(path_to_file)
path = path[0]
#print(path)

points=np.linspace(0,1,10,endpoint=True)
pathvals=np.zeros_like(points,dtype="complex")

pathlength=path.length()
print("pathlength is: ",pathlength)


pathlength is:  1014.1104089718626


In [69]:
# 生
"""
宋体的生计算路径和为无穷
可以手动修改svg的path标签
将一些贝塞尔无线替换成直线
"""

path_to_file = 'A_.svg'
#path_to_file = 'Asheng.svg'

path,_=svgpathtools.svg2paths(path_to_file)
path = path[0]
print(path)

points=np.linspace(0,1,10,endpoint=True)
pathvals=np.zeros_like(points,dtype="complex")

pathlength=path.length()
print("pathlength is: ",pathlength)


Path(Line(start=(175.52847+202.5051j), end=(44.371821+202.5051j)),
     Line(start=(44.371821+202.5051j), end=(44.371821+191.62075j)),
     Line(start=(44.371821+191.62075j), end=(101.10289+191.62075j)),
     Line(start=(101.10289+191.62075j), end=(101.10289+159.77122j)),
     Line(start=(101.10289+159.77122j), end=(59.970926+159.77122j)),
     Line(start=(59.970926+159.77122j), end=(59.970926+148.81382j)),
     Line(start=(59.970926+148.81382j), end=(101.10289+148.81382j)),
     Line(start=(101.10289+148.81382j), end=(101.10289+120.83591j)),
     Line(start=(101.10289+120.83591j), end=(70.137506+120.83591j)),
     QuadraticBezier(start=(70.137506+120.83591j), control=(65.481058+133.40039j), end=(48.71784100000001+150.20175j)),
     Line(start=(48.71784100000001+150.20175j), end=(36.611073+144.0656j)),
     QuadraticBezier(start=(36.611073+144.0656j), control=(63.308048+121.56639j), end=(65.71388+88.401985j)),
     Line(start=(65.71388+88.401985j), end=(77.74304000000001+91.835306j)),


In [29]:
points

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
pathvals

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j])

In [30]:
com_list = [1+2j, 3+4j, 5+6j]
np.conj(com_list)

array([1.-2.j, 3.-4.j, 5.-6.j])

In [36]:
nvec = 11
coefs=list(range(nvec // 2, -nvec// 2, -1))
coefs.sort(key=abs)
coefs

[0, 1, -1, 2, -2, 3, -3, 4, -4, 5, -5]

In [37]:
np.array(coefs)

array([ 0,  1, -1,  2, -2,  3, -3,  4, -4,  5, -5])

In [35]:
import numpy as np

# 示例数据
y = np.array([1, 2, 3, 4])
x = np.array([0, 1, 2, 3])

# 使用 np.trapz 计算积分
integral = np.trapz(y, x)

print(integral)


7.5
