In [5]:
import svgpathtools
import numpy as np

In [2]:
path_to_file = 'A.svg'
path,_=svgpathtools.svg2paths(path_to_file)

In [3]:
path

[Path(Line(start=(62.868614+46.826283j), end=(151.31825+46.826283j)),
      Line(start=(151.31825+46.826283j), end=(151.31825+109.69489j)),
      Line(start=(151.31825+109.69489j), end=(62.868614+109.69489j)),
      Line(start=(62.868614+109.69489j), end=(62.868614+46.826283j)))]

In [23]:
path[0]

Path(Line(start=(62.868614+46.826283j), end=(151.31825+46.826283j)),
     Line(start=(151.31825+46.826283j), end=(151.31825+109.69489j)),
     Line(start=(151.31825+109.69489j), end=(62.868614+109.69489j)),
     Line(start=(62.868614+109.69489j), end=(62.868614+46.826283j)))

In [27]:
((151.31825-62.868614)+(109.69489-46.826283))*2

302.636486

In [24]:
path[0].length()

302.636486

In [28]:
points=np.linspace(0,1,10,endpoint=True)
pathvals=np.zeros_like(points,dtype="complex")

In [29]:
points

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
pathvals

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j])

In [30]:
com_list = [1+2j, 3+4j, 5+6j]
np.conj(com_list)

array([1.-2.j, 3.-4.j, 5.-6.j])

In [32]:
nvec = 11
coefs=list(range(nvec // 2, -nvec// 2, -1))
coefs.sort(key=abs)
coefs

[0, 1, -1, 2, -2, 3, -3, 4, -4, 5]